### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NickB926** [AXOca/Stand-Tools#1]
feature to remove third party avs

and delete one drive?

**Comment by alessandromrc** [comment]
> feature to remove third party avs
> 
> and delete one drive?

This is a Support Tool... Not a tool to remove malware or stuff from your computer...

Either use Linux or uninstall them yourself.

**Comment by AXOca** [comment]
> Feature to remove third-party AVs
Maintaining this feature would be very difficult, if not impossible.

> And delete OneDrive?

While it is possible to delete OneDrive and its unconventional filesystem, this action is likely to cause more harm than good, potentially resulting in lost files and other issues.
